// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xjtf.d;

#nullable disable

namespace xjtf.d.Migrations
{
    [DbContext(typeof(DaemonDbContext))]
    [Migration("20220825024544_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("xjtf.d.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("xjtf.d.ServiceEntry", b =>
                {
                    b.Property<int>("ServiceEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceEntryId");

                    b.ToTable("ServiceEntries");
                });

            modelBuilder.Entity("xjtf.d.ServiceEntryActual", b =>
                {
                    b.Property<int>("ServiceEntryActualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ObservedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceEntryActualId");

                    b.HasIndex("ServiceEntryId");

                    b.ToTable("ServiceEntryActuals");
                });

            modelBuilder.Entity("xjtf.d.ServiceEntryState", b =>
                {
                    b.Property<int>("ServiceEntryStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DaemonManaged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServiceEntryStateId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ServiceEntryId");

                    b.ToTable("ServiceEntryStates");
                });

            modelBuilder.Entity("xjtf.d.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("xjtf.d.Role", b =>
                {
                    b.HasOne("xjtf.d.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("xjtf.d.ServiceEntryActual", b =>
                {
                    b.HasOne("xjtf.d.ServiceEntry", "ServiceEntry")
                        .WithMany()
                        .HasForeignKey("ServiceEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceEntry");
                });

            modelBuilder.Entity("xjtf.d.ServiceEntryState", b =>
                {
                    b.HasOne("xjtf.d.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xjtf.d.ServiceEntry", "ServiceEntry")
                        .WithMany()
                        .HasForeignKey("ServiceEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("ServiceEntry");
                });

            modelBuilder.Entity("xjtf.d.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
